[package]
name = "AeroNyx-Private-Ed25519"
version = "0.1.0"
edition = "2021"
authors = ["hi@aeronyx.network"]
description = "A private server using Solana keypairs for authentication and encryption"

[dependencies]
# Async runtime
tokio = { version = "1.28", features = ["full"] }
futures = "0.3"

# WebSockets
tokio-tungstenite = "0.19"

# Networking
tun = { version = "0.5", features = ["async"] }
socket2 = "0.5"

# Cryptography
solana-sdk = "=1.14.18"
ed25519-dalek = "1.0"
x25519-dalek = "1.2"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
aes = "0.8"
cbc = { version = "0.1", features = ["std"] }
hmac = "0.12"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
clap = { version = "4.3", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

# IP address handling
ipnetwork = "0.20"
